[service]
hosts=127.0.0.1
ports=8080
enabled_ssl=false
certFile="resource/server.crt"
keyFile="resource/server.key"

[mysql]
dbtype="mysql"
hosts="127.0.0.1"
ports="3306"
users="root"
passwd="123456"
dbName="admin"
maxIdleConns=10
maxOpenConns=100

[redis]
enabled=false
hosts=127.0.0.1
ports=6537
db=1
passwd="123456"

[email]
hosts="smtp.163.com"
ports=465
enabled_ssl=false
from="xxx@163.com"
secret="xxx"